"""Phase 0: what data actually exists.

Downloads competitions.json + one small matches index per competition/season
(~75 tiny files, a few MB total). No event files. Writes docs/data_inventory.md.

Run:  python ingest/00_inventory.py
"""
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from core.config import DOCS_DIR  # noqa: E402
from ingest import _http  # noqa: E402


def main():
    comps = _http.competitions()
    print(f"{len(comps)} competition/season rows in competitions.json")

    rows = []
    for c in comps:
        cid, sid = c["competition_id"], c["season_id"]
        ms = _http.matches(cid, sid)
        n = len(ms)
        n360 = sum(1 for m in ms if m.get("match_status_360") == "available")
        dates = sorted(m.get("match_date", "") for m in ms if m.get("match_date"))
        teams = set()
        for m in ms:
            teams.add(m.get("home_team", {}).get("home_team_name"))
            teams.add(m.get("away_team", {}).get("away_team_name"))
        teams.discard(None)
        rows.append(
            dict(
                competition_id=cid,
                season_id=sid,
                competition=c["competition_name"],
                season=c["season_name"],
                gender=c.get("competition_gender", ""),
                matches=n,
                matches_360=n360,
                teams=len(teams),
                first=dates[0] if dates else "",
                last=dates[-1] if dates else "",
            )
        )
        print(f"  {c['competition_name']:<28} {c['season_name']:<10} "
              f"{n:>4} matches, {n360:>4} with 360")

    rows.sort(key=lambda r: (-r["matches_360"], -r["matches"]))
    total = sum(r["matches"] for r in rows)
    total360 = sum(r["matches_360"] for r in rows)

    out = [
        "# Data inventory — StatsBomb Open Data",
        "",
        "Generated by `ingest/00_inventory.py`. Data source: StatsBomb.",
        "",
        f"- competition/season rows: **{len(rows)}**",
        f"- matches available: **{total}**",
        f"- matches with 360 freeze frames: **{total360}**",
        "",
        "Sorted by 360 availability, then match count.",
        "",
        "| comp_id | season_id | competition | season | gender | matches | 360 | teams | first | last |",
        "|--:|--:|---|---|---|--:|--:|--:|---|---|",
    ]
    for r in rows:
        out.append(
            f"| {r['competition_id']} | {r['season_id']} | {r['competition']} | "
            f"{r['season']} | {r['gender']} | {r['matches']} | {r['matches_360']} | "
            f"{r['teams']} | {r['first']} | {r['last']} |"
        )
    out += ["", "## Selection for PitchQuery", "",
            "See `docs/selection.md` — this file is regenerated and would overwrite notes.", ""]

    path = DOCS_DIR / "data_inventory.md"
    path.write_text("\n".join(out), encoding="utf-8")
    print(f"\nwrote {path}")
    print(f"TOTAL: {total} matches, {total360} with 360")
    print("gender split:", Counter(r["gender"] for r in rows))


if __name__ == "__main__":
    main()
